# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bc5fe945a7909964adce29a9a79fb9cb7e8e598ce535024c5117ffd651639f4fa52e3c64c507ba529e7e6b8fbdff59453c595e0a5710104baeb030d6ae22c26

test:
  secret_key_base: 43ddad0d6a8c3790796cc1c4786771b8392552f6a5755468fb8d6b6090d1a5e5f432991e21707bc69b17ecb10d121b9db3521f92ba225fd3c11f295761e54b0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
